### ISSUE TITLE
got fail to install nedgedb in meteor 1.6

### ISSUE THREAD

**Issue by cornga** [z0r0n/nedgedb#3]
Hi Sir,
I got fail to install nedgedb in meteor 1.6.
I read the message>>
Note - This version was written for nodeJs 0.12.0 and is since not 
being updated. This module does not work with latest node versions. 
https://github.com/z0r0n/nedgedb/blob/master/readme.md

Will there be an updated version?
I really need it to use progress openedgeDB.

**Comment by z0r0n** [comment]
Hi, 
There wont be any more updates to this module in this repository. We (the contributors) are not associated with them anymore. 
You may contact the Progress Support Team for more information regarding their latest utility.
